name: Checkmarq Scan

on:
  push:


jobs:
  checkmarq_scan:
    name: Run Checkmarq Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarq Scan
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.6
        with:
          team: /CxServer
          project: PythonProject  
          checkmarx_url: ${{ secrets.MTF_CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.DI_CHECKMARX_USERNAME }}
          checkmarx_password: ${{ secrets.DI_CHECKMARX_PASSWORD }}
          params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --cx-flow.zip-exclude=".git/.*, .github/., node_modules/.*., public/., coverage/., test/., *.svg," --logging.level.com.checkmarx=DEBUG

          scanners: sast
          github_token: ${{ secrets.AUTH }}
