name: "sonar_cloud_scan_github_actions"
on:
 push:

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.6
        with:
          team: /CxServer
          project: DI_ITYPE
          checkmarx_url: ${{ secrets.MTF_CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.DI_CHECKMARX_USERNAME }}
          checkmarx_password: ${{ secrets.DI_CHECKMARX_PASSWORD }}
        #  checkmarx_client_secret: ${{ secrets.MTF_CHECKMARX_CLIENT_SECRET }}
          github_token: ${{ secrets.AUTH }}
